### PR TITLE
v4 Design Implementation

### PR DESCRIPTION
**Pull request by AndreasInk**
Hi @zssz!  I merged the conflicts and added a spacer on the report view's image to place the image on the bottom.  I also tested the changes on smaller screens and larger screens such as the SE and 11.

### CODE REVIEW

**Comment by AndreasInk** [comment]
Hi @zssz, hope all is well!  I implemented the V4 design of the exposures list view (named PossibleExposuresV2 in Xcode) including...

- Added new assets
- Added exposure drop down menu for raw data details 

Next up:

-Implement the backend to the design

For reference the Figma view it is located under Home Screen then return user then exposures list

Hope this helps! Let me know if this is what you envisioned and how it can be improved.

**Comment by zssz** [comment]
Hey! Let's work on the https://github.com/covidwatchorg/covidwatch-ios-en/tree/v4 branch. Can you create a PR for that branch and see if it merges?

**Comment by AndreasInk** [comment]
HI! I can do that!

**Comment by AndreasInk** [comment]
It's mergeable @zssz, let me know if I should merge it.

**Pull request closed without merging**
