### PR TITLE
Report update

### PR DESCRIPTION
**Pull request by AndreasInk**
Hi @zssz! I positioned the report image so it's at the bottom and checked multiple devices for sizing issues and we are all good. Next I'll make the image more dynamic.

### CODE REVIEW

**Comment by zssz** [comment]
Hey! Sorry, for being so slow to respond. Can you fix the merge conflicts? Thank you!

**Comment by AndreasInk** [comment]
Hi! I definitely can! Happy to help!

**Comment by AndreasInk** [comment]
HI @zssz, I'm not sure why I closed this, I'll fix the conflicts now.

**Comment by AndreasInk** [comment]
@zssz It appears that there are no conflicts with the base branch (OnboardingUpdate), do you want me to merge with master or v4 and fix conflicts there?

**Comment by AndreasInk** [comment]
@zssz sorry for the confusion... V4 Design Implementation PR has this update with a bit more and appears mergeable.

**Pull request closed without merging**
